version: "3"
services:
  memcached:
    image: memcached
    command: memcached -l 0.0.0.0 -I 32m  -m 128
    ports:
      - "11211:11211"
  redis:
    image: redis
    ports:
      - "6379:6379"
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: pydici
      MARIADB_USER: pydici
      MARIADB_PASSWORD: pydici
  django:
    build: .
    command: python manage.py runserver_plus 0.0.0.0:8888
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - memcached
      - redis
      - mariadb
  celery:
    build: .
    command: celery -A pydici worker -B -l INFO
    volumes:
      - .:/code
    depends_on:
      - django