name: pydici test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with django test
      run: |
        docker-compose run --use-aliases --service-ports django python manage.py test
